[book]
title = "InTimeScope"
authors = ["kyohah"]

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kyohah/in_time_scope"
edit-url-template = "https://github.com/kyohah/in_time_scope/edit/main/docs/{path}"

[language]
[language.en]
name = "English"
title = "InTimeScope"

[language.ja]
name = "日本語"
title = "InTimeScope"

[language.zh]
name = "中文"
title = "InTimeScope"

[language.de]
name = "Deutsch"
title = "InTimeScope"

[language.fr]
name = "Français"
title = "InTimeScope"
