[book]
title = "InTimeScope"
authors = ["kyohah"]
language = "de"
multilingual = false
src = "de"

[build]
build-dir = "book/de"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/kyohah/in_time_scope"
edit-url-template = "https://github.com/kyohah/in_time_scope/edit/main/docs/{path}"
